# Generated by Django 3.2.16 on 2022-11-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('author', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
